export const TYPE_COLORS: Record<string, string> = {
  prayer: "#34d399",
  routine: "#6b8afd",
  spiritual: "#a78bfa",
  execution: "#fbbf24",
  personal: "#fb923c",
  build: "#38bdf8",
  company: "#f87171",
  logistics: "#94a3b8",
  recovery: "#4ade80",
  admin: "#d4a054",
  "r&d": "#c084fc",
  review: "#2dd4bf",
  product: "#60a5fa",
  visibility: "#fb923c",
};

export const DEFAULT_BLOCKS = [
  { blockId: "wake", start: "04:30", end: "04:35", title: "Wake, wudu, and stand up immediately", note: "No snooze. Drink water and move within 60 seconds.", location: "away" as const, priority: "must" as const, type: "routine" },
  { blockId: "fajr", start: "04:35", end: "04:50", title: "Fajr salah", note: "Anchor your day spiritually before work starts.", location: "away" as const, priority: "must" as const, type: "prayer" },
  { blockId: "quran", start: "04:50", end: "05:20", title: "Quran recitation (30 min)", note: "Keep it calm and consistent.", location: "away" as const, priority: "must" as const, type: "spiritual" },
  { blockId: "small-win", start: "05:20", end: "05:40", title: "Small early win", note: "Goal: one finished task to build momentum.", location: "desk" as const, priority: "must" as const, type: "execution" },
  { blockId: "family-breakfast", start: "05:40", end: "06:10", title: "Family touchpoint + breakfast prep", note: "Reduce pressure early so later focus is cleaner.", location: "away" as const, priority: "must" as const, type: "personal" },
  { blockId: "wing-idea", start: "06:10", end: "07:10", title: "Wingmic: gather cloud notes + planning chat", note: "Distill scope into one sharp concept.", location: "desk" as const, priority: "must" as const, type: "product" },
  { blockId: "wing-landing", start: "07:10", end: "08:40", title: "Wingmic: combine design + start repo + landing v0", note: "Ship visible progress. Avoid over-engineering.", location: "desk" as const, priority: "must" as const, type: "build" },
  { blockId: "social-post", start: "08:40", end: "09:00", title: "Build-in-public update (first social post)", note: "Publish even if short.", location: "desk" as const, priority: "must" as const, type: "visibility" },
  { blockId: "move-1", start: "09:00", end: "13:00", title: "Move logistics block", note: "Primary away-from-desk block.", location: "away" as const, priority: "must" as const, type: "logistics" },
  { blockId: "dhuhr", start: "13:00", end: "13:20", title: "Dhuhr / Zohar salah", note: "Reset and avoid rushing into desk work without pause.", location: "away" as const, priority: "must" as const, type: "prayer" },
  { blockId: "move-2", start: "13:20", end: "14:00", title: "Settle at new location + quick recovery", note: "Food/water/reset before cognitive tasks.", location: "away" as const, priority: "must" as const, type: "recovery" },
  { blockId: "admin", start: "14:00", end: "14:45", title: "Admin sprint", note: "Finish both completely in one sitting.", location: "desk" as const, priority: "should" as const, type: "admin" },
  { blockId: "merge-1", start: "14:45", end: "16:45", title: "Company merge sprint 1", note: "Audit branch diffs, set merge order, start conflict resolution.", location: "desk" as const, priority: "must" as const, type: "company" },
  { blockId: "asar", start: "17:00", end: "17:20", title: "Asar salah", note: "Step away and reset attention.", location: "away" as const, priority: "must" as const, type: "prayer" },
  { blockId: "merge-2", start: "17:20", end: "19:50", title: "Company merge sprint 2", note: "Continue staged merges + review notes.", location: "desk" as const, priority: "must" as const, type: "company" },
  { blockId: "maghrib", start: "20:00", end: "20:20", title: "Maghrib salah", note: "Natural checkpoint before evening block.", location: "away" as const, priority: "must" as const, type: "prayer" },
  { blockId: "thesis-lab", start: "20:20", end: "21:15", title: "Thesis.dev UI/chat experiments (time-boxed)", note: "Experimental only. Stop on time.", location: "desk" as const, priority: "stretch" as const, type: "r&d" },
  { blockId: "isha", start: "21:30", end: "21:50", title: "Isha salah", note: "Close major loops mentally.", location: "away" as const, priority: "must" as const, type: "prayer" },
  { blockId: "shutdown", start: "21:50", end: "22:10", title: "Shutdown review + tomorrow prep", note: "Log what shipped, blockers, and first task for next day.", location: "desk" as const, priority: "must" as const, type: "review" },
];
